// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a87zscS5zAyxUWqfaRXyok
// Component: Y6zlynpCxa3uIT
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: SpLhEqEri3lkmA/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: a87zscS5zAyxUWqfaRXyok/projectcss
import * as sty from "./PlasmicValue.module.css"; // plasmic-import: Y6zlynpCxa3uIT/css
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: fx6UOFDfBvrPWK/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: WJfArt8fdpayFX/icon

export const PlasmicValue__VariantProps = new Array(
  "topBottom",
  "center",
  "withButton"
);

export const PlasmicValue__ArgProps = new Array(
  "children",
  "slot",
  "children2"
);

function PlasmicValue__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__center]: hasVariant(variants, "center", "center"),
        [sty.root__topBottom]: hasVariant(variants, "topBottom", "topBottom"),
        [sty.root__withButton]: hasVariant(variants, "withButton", "withButton")
      })}
    >
      <div
        className={classNames(defaultcss.all, sty.box__n6FUl, {
          [sty.box__center__n6FULw7OCr]: hasVariant(
            variants,
            "center",
            "center"
          ),

          [sty.box__topBottom__n6FULgY52W]: hasVariant(
            variants,
            "topBottom",
            "topBottom"
          )
        })}
      >
        <div className={classNames(defaultcss.all, sty.box__usrc2)}>
          {p.renderPlasmicSlot({
            defaultContents: (
              <Icon9Icon
                className={classNames(defaultcss.all, sty.svg__wrUtG)}
                role={"img"}
              />
            ),

            value: args.slot
          })}
        </div>
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__fxK07, {
          [sty.box__center__fxK07W7OCr]: hasVariant(
            variants,
            "center",
            "center"
          ),

          [sty.box__withButton__fxK07Cg8L8]: hasVariant(
            variants,
            "withButton",
            "withButton"
          )
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box___2FAz5
                )}
              >
                {"Worldwide Shipping"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__dFutH
                )}
              >
                {"Special financing and earn rewards."}
              </div>
            </React.Fragment>
          ),

          value: args.children,
          className: classNames(sty.slotChildren, {
            [sty.slotChildren__center]: hasVariant(variants, "center", "center")
          })
        })}
      </p.Stack>

      {(hasVariant(variants, "withButton", "withButton") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box___3ZoWj, {
            [sty.box__center___3ZoWJw7OCr]: hasVariant(
              variants,
              "center",
              "center"
            ),

            [sty.box__withButton___3ZoWJcg8L8]: hasVariant(
              variants,
              "withButton",
              "withButton"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <Button
                children2={
                  <Icon5Icon
                    className={classNames(defaultcss.all, sty.svg__fmMg)}
                    role={"img"}
                  />
                }
                className={classNames("__wab_instance", sty.button__aFlUr, {
                  [sty.button__withButton__aFlUrcg8L8]: hasVariant(
                    variants,
                    "withButton",
                    "withButton"
                  )
                })}
                colors={"black"}
                icons={"end"}
                rounded={"rounded"}
                size={"large"}
                slot={"Read our letter"}
              />
            ),

            value: args.children2,
            className: classNames(sty.slotChildren2, {
              [sty.slotChildren2__center]: hasVariant(
                variants,
                "center",
                "center"
              ),

              [sty.slotChildren2__withButton]: hasVariant(
                variants,
                "withButton",
                "withButton"
              )
            })
          })}
        </p.Stack>
      ) : null}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicValue__ArgProps,
      internalVariantPropNames: PlasmicValue__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicValue__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValue";
  } else {
    func.displayName = `PlasmicValue.${nodeName}`;
  }
  return func;
}

export const PlasmicValue = Object.assign(
  // Top-level PlasmicValue renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicValue
    internalVariantProps: PlasmicValue__VariantProps,
    internalArgProps: PlasmicValue__ArgProps
  }
);

export default PlasmicValue;
/* prettier-ignore-end */
