// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a87zscS5zAyxUWqfaRXyok
// Component: Di1OOkJnVvkllM
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: MpeH7ry8BRWLQD/component
import CartItem from "../../CartItem"; // plasmic-import: Hh_PecjMJgfGYO/component
import Button from "../../Button"; // plasmic-import: SpLhEqEri3lkmA/component
import Separator from "../../Separator"; // plasmic-import: G27rD6X62-BLct/component
import Footer from "../../Footer"; // plasmic-import: BJB9TNf3xCMxyU/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: t4DeUfbUb9lt6-/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: a87zscS5zAyxUWqfaRXyok/projectcss
import * as sty from "./PlasmicCart.module.css"; // plasmic-import: Di1OOkJnVvkllM/css
import Icon31Icon from "./icons/PlasmicIcon__Icon31"; // plasmic-import: lWS44Ldr4CrIgJ/icon
import Icon32Icon from "./icons/PlasmicIcon__Icon32"; // plasmic-import: L6dI6jzdWCmF-a/icon
import Icon30Icon from "./icons/PlasmicIcon__Icon30"; // plasmic-import: 6pNxp5MorT2SeF/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: 42A6AiDsLrw6Xb/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: X42BYSFS5AGQRe/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: BzKeHVANHFAxLc/icon
import imageTlH4ZIyUbftrB from "./images/image.svg"; // plasmic-import: tl-h4zIYUbftrB/picture
import image2VG8AxTucnhvmqC from "./images/image2.svg"; // plasmic-import: vG8AxTucnhvmqC/picture
import image3OvRoogfztZ1Ol from "./images/image3.svg"; // plasmic-import: OV_roogfztZ1OL/picture
import image4WLwScW0TqSheId from "./images/image4.svg"; // plasmic-import: wLWScW0TqSheID/picture

export const PlasmicCart__VariantProps = new Array("filled");

export const PlasmicCart__ArgProps = new Array(
  "children",
  "slot",
  "slot2",
  "slot3",
  "slot4",
  "slot5"
);

function PlasmicCart__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root,
            { [sty.root__filled]: hasVariant(variants, "filled", "filled") }
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar, {
              [sty.navBar__filled]: hasVariant(variants, "filled", "filled")
            })}
            filled={
              hasVariant(variants, "filled", "filled") ? "filled" : undefined
            }
          />

          <p.Stack
            as={"section"}
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            hasGap={true}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container2, {
                [sty.container2__filled]: hasVariant(
                  variants,
                  "filled",
                  "filled"
                )
              })}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__sZmiw, {
                  [sty.box__filled__sZmiwlIiw4]: hasVariant(
                    variants,
                    "filled",
                    "filled"
                  )
                })}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__wilTq,
                    {
                      [sty.box__filled__wilTQlIiw4]: hasVariant(
                        variants,
                        "filled",
                        "filled"
                      )
                    }
                  )}
                >
                  {hasVariant(variants, "filled", "filled")
                    ? "Your bag (1)"
                    : "Looks like your bag is empty"}
                </div>

                {(hasVariant(variants, "filled", "filled") ? true : false) ? (
                  <CartItem
                    data-plasmic-name={"cartItem"}
                    data-plasmic-override={overrides.cartItem}
                    className={classNames("__wab_instance", sty.cartItem, {
                      [sty.cartItem__filled]: hasVariant(
                        variants,
                        "filled",
                        "filled"
                      )
                    })}
                  >
                    <a
                      data-plasmic-name={"link"}
                      data-plasmic-override={overrides.link}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.link
                      )}
                    >
                      {"Eternity NITRO Men's Running Shoes"}
                    </a>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__jqQxi
                      )}
                    >
                      {"#00000"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__ompkS
                      )}
                    >
                      {"Size: 11"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__r4VPt
                      )}
                    >
                      {"Quantity: 1"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__vwkBm)}
                    >
                      <Icon31Icon
                        className={classNames(defaultcss.all, sty.svg__eahjh)}
                        role={"img"}
                      />

                      <Icon32Icon
                        className={classNames(defaultcss.all, sty.svg__rywS)}
                        role={"img"}
                      />
                    </p.Stack>
                  </CartItem>
                ) : null}

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__cFhbA,
                    {
                      [sty.box__filled__cFhbAlIiw4]: hasVariant(
                        variants,
                        "filled",
                        "filled"
                      )
                    }
                  )}
                >
                  {
                    "If you have an account, please sign in to see items you previously added."
                  }
                </div>

                <Button
                  colors={"black"}
                  icons={"none"}
                  rounded={"rounded"}
                  size={"large"}
                  slot={"Login"}
                />

                <Button
                  colors={"white"}
                  icons={"none"}
                  rounded={"rounded"}
                  slot={"Continue shopping"}
                />

                {(hasVariant(variants, "filled", "filled") ? false : false) ? (
                  <div
                    className={classNames(defaultcss.all, sty.box__w8Oeq, {
                      [sty.box__filled__w8OeQlIiw4]: hasVariant(
                        variants,
                        "filled",
                        "filled"
                      )
                    })}
                  />
                ) : null}
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__b9ZMv, {
                  [sty.box__filled__b9ZMVlIiw4]: hasVariant(
                    variants,
                    "filled",
                    "filled"
                  )
                })}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__nkJrQ, {
                    [sty.box__filled__nkJrQlIiw4]: hasVariant(
                      variants,
                      "filled",
                      "filled"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__wAgx9,
                      {
                        [sty.box__filled__wAgx9LIiw4]: hasVariant(
                          variants,
                          "filled",
                          "filled"
                        )
                      }
                    )}
                  >
                    {"Order Summary"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__rWeKh, {
                      [sty.box__filled__rWeKhlIiw4]: hasVariant(
                        variants,
                        "filled",
                        "filled"
                      )
                    })}
                  >
                    <div className={classNames(defaultcss.all, sty.box__iSv8V)}>
                      <div
                        className={classNames(defaultcss.all, sty.box__nr4Wh, {
                          [sty.box__filled__nr4WHlIiw4]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        })}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "Subtotal (1)"
                            : "Subtotal (0)",
                          value: args.slot5,
                          className: classNames(sty.slotSlot5, {
                            [sty.slotSlot5__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>

                      <div
                        className={classNames(defaultcss.all, sty.box__bsw3, {
                          [sty.box__filled__bsw3LIiw4]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        })}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "$88.99"
                            : "$0.00",
                          value: args.children,
                          className: classNames(sty.slotChildren, {
                            [sty.slotChildren__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    <div className={classNames(defaultcss.all, sty.box___59Bl)}>
                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__xOp8M,
                            {
                              [sty.box__filled__xOp8MlIiw4]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Estimated Shipping (free over $49)"}
                        </div>
                      ) : null}

                      <div
                        className={classNames(defaultcss.all, sty.box__ctsRt, {
                          [sty.box__filled__ctsRTlIiw4]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        })}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "FREE"
                            : "-",
                          value: args.slot,
                          className: classNames(sty.slotSlot, {
                            [sty.slotSlot__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    <div className={classNames(defaultcss.all, sty.box__d6CmM)}>
                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__rwDhi,
                            {
                              [sty.box__filled__rwDhilIiw4]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Estimated Tax"}
                        </div>
                      ) : null}

                      <div
                        className={classNames(defaultcss.all, sty.box__xlug4, {
                          [sty.box__filled__xlug4LIiw4]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        })}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: "-",
                          value: args.slot2,
                          className: classNames(sty.slotSlot2, {
                            [sty.slotSlot2__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___3GfpD,
                        {
                          [sty.button__filled___3GfpDlIiw4]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        }
                      )}
                      icons={"none"}
                      link={"link"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__vt0E
                          )}
                        >
                          {"Have a promo code?"}
                        </div>
                      }
                    />

                    <Separator
                      data-plasmic-name={"separator"}
                      data-plasmic-override={overrides.separator}
                      className={classNames("__wab_instance", sty.separator)}
                      dark={"dark"}
                    />

                    <div
                      className={classNames(defaultcss.all, sty.box__aMwgV, {
                        [sty.box__filled__aMwgVlIiw4]: hasVariant(
                          variants,
                          "filled",
                          "filled"
                        )
                      })}
                    >
                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__iOdkl,
                            {
                              [sty.box__filled__iOdkllIiw4]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Estimated Total"}
                        </div>
                      ) : null}

                      <div
                        className={classNames(defaultcss.all, sty.box__fV5Ad, {
                          [sty.box__filled__fV5AdlIiw4]: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                        })}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: hasVariant(
                            variants,
                            "filled",
                            "filled"
                          )
                            ? "$88.99"
                            : "$0.00",
                          value: args.slot4,
                          className: classNames(sty.slotSlot4, {
                            [sty.slotSlot4__filled]: hasVariant(
                              variants,
                              "filled",
                              "filled"
                            )
                          })
                        })}
                      </div>
                    </div>

                    {(hasVariant(variants, "filled", "filled") ? true : false)
                      ? p.renderPlasmicSlot({
                          defaultContents: true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button___8M3Au
                              )}
                              colors={"blue"}
                              icons={"none"}
                              rounded={"rounded"}
                              size={"large"}
                              slot={
                                <div
                                  className={classNames(
                                    defaultcss.all,
                                    defaultcss.__wab_text,
                                    sty.box__jddVg
                                  )}
                                >
                                  {"Checkout"}
                                </div>
                              }
                            />
                          ) : null,
                          value: args.slot3
                        })
                      : null}

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__oxvV, {
                        [sty.box__filled__oxvVlIiw4]: hasVariant(
                          variants,
                          "filled",
                          "filled"
                        )
                      })}
                    >
                      <Icon30Icon
                        className={classNames(defaultcss.all, sty.svg__oxPcH)}
                        role={"img"}
                      />

                      {(
                        hasVariant(variants, "filled", "filled") ? true : true
                      ) ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__bbBbZ,
                            {
                              [sty.box__filled__bbBbZlIiw4]: hasVariant(
                                variants,
                                "filled",
                                "filled"
                              )
                            }
                          )}
                        >
                          {"Secure"}
                        </div>
                      ) : null}
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__jBm6F, {
                    [sty.box__filled__jBm6FlIiw4]: hasVariant(
                      variants,
                      "filled",
                      "filled"
                    )
                  })}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__t16U)}
                    role={"img"}
                    src={imageTlH4ZIyUbftrB}
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ga5S3)}
                    role={"img"}
                    src={image2VG8AxTucnhvmqC}
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__z2JEq)}
                    role={"img"}
                    src={image3OvRoogfztZ1Ol}
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__c5BsP)}
                    role={"img"}
                    src={image4WLwScW0TqSheId}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container, {
                [sty.container__filled]: hasVariant(
                  variants,
                  "filled",
                  "filled"
                )
              })}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__wRpI)}
                role={"img"}
                src={
                  "https://www.patagonia.com/on/demandware.static/-/Library-Sites-PatagoniaShared/default/dw4b201dc8/images/for-the-planet.png"
                }
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__oFlu)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__hZehT
                  )}
                >
                  {"1% of your purchase will go to a grassroot organization."}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__h6Su)}
                  icons={"none"}
                  link={"link"}
                  slot={"Learn more"}
                />
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__o3WHw)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nQcCu
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___2MGE
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…"}
                    size={1}
                    type={"text"}
                    value={""}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__r9Kcq)}
                    colors={"black"}
                    icons={"none"}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__oQZvz)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__fs4Zx
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__plomb)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__zoYbN)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__th52A
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__rbg5O
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__bTD)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__fEdrs
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__oS10R
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg___6O27D)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box___8Qv7F)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___9J0G
                    )}
                  >
                    {"More info"}
                  </div>

                  <div className={classNames(defaultcss.all, sty.box__uZvwj)}>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__rJyCq)}
                    >
                      <Button icons={"none"} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__hwDi
                        )}
                        icons={"none"}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__lAgov
                        )}
                        icons={"none"}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__eswTx
                        )}
                        icons={"none"}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__igTj5)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__toHus
                        )}
                        icons={"none"}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__pf14F
                        )}
                        icons={"none"}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__yd3Uo
                        )}
                        icons={"none"}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "section",
    "container2",
    "cartItem",
    "link",
    "separator",
    "container",
    "footer",
    "textbox"
  ],

  navBar: ["navBar"],
  section: [
    "section",
    "container2",
    "cartItem",
    "link",
    "separator",
    "container"
  ],

  container2: ["container2", "cartItem", "link", "separator"],
  cartItem: ["cartItem", "link"],
  link: ["link"],
  separator: ["separator"],
  container: ["container"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCart__ArgProps,
      internalVariantPropNames: PlasmicCart__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicCart__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCart";
  } else {
    func.displayName = `PlasmicCart.${nodeName}`;
  }
  return func;
}

export const PlasmicCart = Object.assign(
  // Top-level PlasmicCart renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container2: makeNodeComponent("container2"),
    cartItem: makeNodeComponent("cartItem"),
    link: makeNodeComponent("link"),
    separator: makeNodeComponent("separator"),
    container: makeNodeComponent("container"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicCart
    internalVariantProps: PlasmicCart__VariantProps,
    internalArgProps: PlasmicCart__ArgProps
  }
);

export default PlasmicCart;
/* prettier-ignore-end */
