// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a87zscS5zAyxUWqfaRXyok
// Component: 3hnKrVti0MEako
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: MpeH7ry8BRWLQD/component
import Button from "../../Button"; // plasmic-import: SpLhEqEri3lkmA/component
import ProductCard from "../../ProductCard"; // plasmic-import: 5q6vu0sOZbzTG_/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: AVTVbykJqn_B38/component
import Value from "../../Value"; // plasmic-import: Y6zlynpCxa3uIT/component
import Footer from "../../Footer"; // plasmic-import: BJB9TNf3xCMxyU/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: t4DeUfbUb9lt6-/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: a87zscS5zAyxUWqfaRXyok/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: 3hnKrVti0MEako/css
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: WJfArt8fdpayFX/icon
import Icon23Icon from "./icons/PlasmicIcon__Icon23"; // plasmic-import: WRIF1ywEnG5Y2j/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: s49MDf-BqjfY-z/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: Qk8wqgcrz4uaiz/icon
import Icon18Icon from "./icons/PlasmicIcon__Icon18"; // plasmic-import: oknYJZbUKMn1Jl/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: pwhoP9QRWUlDAs/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: 42A6AiDsLrw6Xb/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: X42BYSFS5AGQRe/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: BzKeHVANHFAxLc/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array(
  "children",
  "children2",
  "children22",
  "children222",
  "children2222",
  "children22222",
  "container42",
  "children4",
  "children24",
  "children224",
  "children2224",
  "children22224",
  "children222223"
);

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section__ochMg)}>
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__lDcTb)}
              role={"img"}
              src={
                "https://images.unsplash.com/photo-1522158073024-fb5d4b4ccfdf?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2048&q=80"
              }
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__jRm6W)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__yhkz0)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      defaultcss.h1,
                      defaultcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"New collection "}
                  </h1>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ok1HW
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </p.Stack>

                <Button
                  children2={
                    <Icon5Icon
                      className={classNames(defaultcss.all, sty.svg__m4Gw2)}
                      role={"img"}
                    />
                  }
                  className={classNames("__wab_instance", sty.button__puDsk)}
                  colors={"black"}
                  icons={"end"}
                  link2={"/category"}
                  rounded={"rounded"}
                  size={"large"}
                  slot={"Shop"}
                />
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__fxHkv)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(defaultcss.all, sty.container4)}
            >
              <div className={classNames(defaultcss.all, sty.box__hGxWb)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__bot1T
                  )}
                >
                  {"Featured"}
                </div>

                <Button
                  children2={
                    <Icon5Icon
                      className={classNames(defaultcss.all, sty.svg___08WA)}
                      role={"img"}
                    />
                  }
                  className={classNames("__wab_instance", sty.button__cHp2M)}
                  icons={"end"}
                  link={"link"}
                  link2={"/category"}
                  slot={"See more"}
                />
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__eZqV)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__gFhJz)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/1070aebbb55841e1aae5ac9f00b39879_9366/adidas_Ultraboost_DNA_x_LEGO(r)_Plates_Shoes_White_FY7690_01_standard.jpg"
                      }
                    />
                  ),

                  value: args.children
                })}
                link={"/item"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__dRzvo
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__wXii6
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__b1Q2)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__jgfHw)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/79d40e0b-da9d-4049-a4be-6a8fe7d9489e/air-zoom-pegasus-38-womens-running-shoe-2bvJvW.png"
                      }
                    />
                  ),

                  value: args.children2
                })}
                link={"/item"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__iAxli
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__f4Syo
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___2LgaD
                )}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__eEoU)}
                      role={"img"}
                      src={
                        "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/3108369a42714ba6a9c2aa99017b457a_9366/Club_C_85_Vintage_Men's_Shoes_White_V67899_01_standard.jpg"
                      }
                    />
                  ),

                  value: args.children22
                })}
                link={"/item"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__icoNe
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__koT35
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__icSco)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__nikqA)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b13d4f77-9404-492f-b2c8-5f06419f2cb6/air-max-genome-mens-shoe-hgsQFb.png"
                      }
                    />
                  ),

                  value: args.children222
                })}
                link={"/item"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__waJqn
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___8Jay3
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___9PfFd
                )}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__rEvdn)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/cdfdf1409e054322b9e0ac6d011da5e2_9366/Ultraboost_DNA_1.0_Shoes_Green_H05264_01_standard.jpg"
                      }
                    />
                  ),

                  value: args.children2222
                })}
                link={"/item"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__gm9Tx
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__gpe6K
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__a4YH1)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__icBnO)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f6cbde42-eed6-42bd-b5d9-1b5bef129618/zion-1-big-kids-shoe-BsvRq7.png"
                      }
                    />
                  ),

                  value: args.children22222
                })}
                link={"/item"}
              />
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__eukaE)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container43"}
              data-plasmic-override={overrides.container43}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container43)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__rkQm)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__teyzf)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___3ANhx
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__sLsAn
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now’s the perfect time to save on iconic shoes."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__djZ68)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__fgawz
                    )}
                  >
                    <span>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span style={{ fontStyle: "italic" }}>{"for"}</span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </span>
                  </div>

                  <Button
                    children2={
                      <Icon5Icon
                        className={classNames(defaultcss.all, sty.svg__lnji1)}
                        role={"img"}
                      />
                    }
                    colors={"black"}
                    icons={"end"}
                    link2={"/category"}
                    rounded={"rounded"}
                    size={"large"}
                    slot={"Shop sale"}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          />

          <section className={classNames(defaultcss.all, sty.section__bi1Fc)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(defaultcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div className={classNames(defaultcss.all, sty.box__j8AKz)}>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__wXbJg
                      )}
                    >
                      {"Just added"}
                    </div>

                    <Button
                      children2={
                        <Icon5Icon
                          className={classNames(defaultcss.all, sty.svg__cjz5H)}
                          role={"img"}
                        />
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.button__scy3Z
                      )}
                      icons={"end"}
                      link={"link"}
                      link2={"/category"}
                      slot={"See more"}
                    />
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(defaultcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__weo1A)}
              >
                <ProductCard
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__yZBzn)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/1070aebbb55841e1aae5ac9f00b39879_9366/adidas_Ultraboost_DNA_x_LEGO(r)_Plates_Shoes_White_FY7690_01_standard.jpg"
                        }
                      />
                    ),

                    value: args.children4
                  })}
                  link={"http://google.com"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ky06N
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__oSOg
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nKsOc
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__nhEqi)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/79d40e0b-da9d-4049-a4be-6a8fe7d9489e/air-zoom-pegasus-38-womens-running-shoe-2bvJvW.png"
                        }
                      />
                    ),

                    value: args.children24
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___0P3HI
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___1RX7B
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__kJbC
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__bBv2B)}
                        role={"img"}
                        src={
                          "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/3108369a42714ba6a9c2aa99017b457a_9366/Club_C_85_Vintage_Men's_Shoes_White_V67899_01_standard.jpg"
                        }
                      />
                    ),

                    value: args.children224
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___1XSkb
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__dUr7U
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ep5Eg
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___1RYUw)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b13d4f77-9404-492f-b2c8-5f06419f2cb6/air-max-genome-mens-shoe-hgsQFb.png"
                        }
                      />
                    ),

                    value: args.children2224
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__pjP5
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__htFx
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cf17L
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__cz0Ui)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/cdfdf1409e054322b9e0ac6d011da5e2_9366/Ultraboost_DNA_1.0_Shoes_Green_H05264_01_standard.jpg"
                        }
                      />
                    ),

                    value: args.children22224
                  })}
                  link={"/item"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__mlF85
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__q21K4
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__qYktq
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__ckjij)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f6cbde42-eed6-42bd-b5d9-1b5bef129618/zion-1-big-kids-shoe-BsvRq7.png"
                        }
                      />
                    ),

                    value: args.children222223
                  })}
                  link={"http://google.com"}
                />
              </p.Stack>
            </div>
          </section>

          <section className={classNames(defaultcss.all, sty.section__cuMIv)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__duUkL)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__z8D1
                  )}
                >
                  {"Categories"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__k1YO8)}
                  icons={"none"}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__pAyGx
                      )}
                    >
                      {"All"}
                    </div>
                  }
                  states={"active"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__csXoe)}
                  icons={"none"}
                  slot={"New"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__hjWdx)}
                  icons={"none"}
                  slot={"Womens"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__etshB)}
                  icons={"none"}
                  slot={"Mens"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__zyujH)}
                  icons={"none"}
                  slot={"Kids"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__bygp0)}
                  icons={"none"}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__dhhKi
                      )}
                    >
                      {"On sale"}
                    </div>
                  }
                />
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__c2VdW)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___0ZDw9
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__wrBgU)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/0a659aab-5bb4-471e-adb3-beaf9be6e737/air-zoom-pegasus-38-limited-edition-womens-running-shoe-vmTQVG.png"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__d8Pmx
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tWbp
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aq7Bc
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__pC2Y3)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/32735c84c423487da282ac790116ced8_9366/NMD_R1_Shoes_Blue_G55574_01_standard.jpg"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__dmkHz
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__rgY65
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ywQt1
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__uLjWq)}
                      role={"img"}
                      src={
                        "https://assets.reebok.com/images/w_320,f_auto,q_auto:sensitive,fl_lossy/dc6b2176848c4116b789acde0138ff10_9366/Question_Low_Men's_Basketball_Shoes_White_GV7629_01_standard.jpg"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__mx3Kv
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__jq5Ov
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__v2OL
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__rSmjb)}
                      role={"img"}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369155/04/sv03/fnd/PNA/fmt/png/Cali-Women's-Sneakers"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tt8Z
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__dejOb
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__dDtY2
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__ahJB)}
                      role={"img"}
                      src={
                        "https://images.asics.com/is/image/asics/1011B026_600_SR_RT_GLB?$zoom$"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tLlbN
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___2XzD4
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tSeYb
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__bcKu9)}
                      role={"img"}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwfa98a04a/images/a_107/170823C_A_107X1.jpg?sw=964"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tnBv0
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___4VwIm
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bnMdN
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__ejFqO)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c636bdcc-1f55-4cf5-9113-021b47c2fa86/air-zoom-pegasus-38-womens-running-shoe-wide-5JxKzR.png"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__cUHdi
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__aJ52T
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__k5HeG
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__z9Rex)}
                      role={"img"}
                      src={
                        "https://images.asics.com/is/image/asics/1011A780_100_SR_RT_GLB?$zoom$"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__jv4Ih
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__mtHq4
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__t531H
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__jm7Yv)}
                      role={"img"}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw388d0c95/images/a_107/670880C_A_107X1.jpg?sw=964"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__q1Vrh
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tKrBa
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tGoJi
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__edP7)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto:sensitive,fl_lossy/f63138f38e4f4469beaaacdb00fd9b89_9366/nmd_r1-shoes.jpg"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__cS3Yp
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___5822O
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nWySl
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__zToBw)}
                      role={"img"}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380566/01/sv03/fnd/PNA/fmt/png/Suede-Teams-Little-Kids'-Shoes"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__xgOsd
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___14Zw
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tvz06
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__qa458)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/226467aefe794e47a1ddac7201151dfa_9366/Superstar_360_Primeblue_Sandals_Yellow_FX4934_01_standard.jpg"
                      }
                    />
                  }
                  link={"/item"}
                  small={"small"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tVe1O
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__qTxlD
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__g0Lzg)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container434)}
            >
              <Value
                center={"center"}
                children2={
                  <Button
                    children2={
                      <Icon5Icon
                        className={classNames(defaultcss.all, sty.svg__yOft3)}
                        role={"img"}
                      />
                    }
                    className={classNames("__wab_instance", sty.button__zhvNy)}
                    colors={"black"}
                    icons={"end"}
                    rounded={"rounded"}
                    slot={"Read our letter"}
                  />
                }
                className={classNames("__wab_instance", sty.value__dstFl)}
                slot={
                  <Icon23Icon
                    className={classNames(defaultcss.all, sty.svg__dUaRn)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom"}
                withButton={"withButton"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__jmuwz
                  )}
                >
                  {"Our goals"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__y7SPt
                  )}
                >
                  {"We’re learning how to become a new kind of company."}
                </div>
              </Value>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__xSnS)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container433)}
            >
              <Value
                className={classNames("__wab_instance", sty.value__dK3L)}
                slot={
                  <Icon16Icon
                    className={classNames(defaultcss.all, sty.svg__aByp)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__vVrAt
                  )}
                >
                  {"We guarantee everything we sell."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__jd1M
                  )}
                >
                  {
                    "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__jwXff)}
                  icons={"none"}
                  link={"link"}
                  slot={"View guarantee"}
                />
              </Value>

              <Value
                className={classNames("__wab_instance", sty.value___3KDg)}
                slot={
                  <Icon19Icon
                    className={classNames(defaultcss.all, sty.svg__q9Be5)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___5IUu
                  )}
                >
                  {"Know how your shoes are made."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__yXBbe
                  )}
                >
                  {
                    "Parturient blandit viverra blandit sem suspendisse himenaeos."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__bInjz)}
                  icons={"none"}
                  link={"link"}
                />
              </Value>

              <Value
                className={classNames("__wab_instance", sty.value__umOFo)}
                slot={
                  <Icon18Icon
                    className={classNames(defaultcss.all, sty.svg___4OqFi)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__rovv5
                  )}
                >
                  {"Keep your shoes in play."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__pulrl
                  )}
                >
                  {
                    "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button___8V1Qx)}
                  icons={"none"}
                  link={"link"}
                />
              </Value>

              <Value
                className={classNames("__wab_instance", sty.value__a2DXi)}
                slot={
                  <Icon17Icon
                    className={classNames(defaultcss.all, sty.svg__ll7TQ)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__lFn0S
                  )}
                >
                  {"We give back for every sale."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__vO80K
                  )}
                >
                  {
                    "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__ePx1V)}
                  icons={"none"}
                  link={"link"}
                />
              </Value>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__gJuSv)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ldws
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__jnSk4
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…"}
                    size={1}
                    type={"text"}
                    value={""}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__dlZ9L)}
                    colors={"black"}
                    icons={"none"}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box___0X0Nb)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___8Ygrx
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__vNf2N)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__xkGxX)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__cRDnQ
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__wpd62
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__x1Gzw)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__sSxfO
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__u27Ie
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__o5TNh)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box___5QOto)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___1Bo3N
                    )}
                  >
                    {"More info"}
                  </div>

                  <div className={classNames(defaultcss.all, sty.box__v0KRz)}>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__m1XhM)}
                    >
                      <Button icons={"none"} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__qH4Wk
                        )}
                        icons={"none"}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__jbKrd
                        )}
                        icons={"none"}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__wcSHc
                        )}
                        icons={"none"}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__sPBuU)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__zigGc
                        )}
                        icons={"none"}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__iMQm
                        )}
                        icons={"none"}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ekjB
                        )}
                        icons={"none"}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "container",
    "container43",
    "emojiValueProps",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer",
    "textbox"
  ],

  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  container43: ["container43"],
  emojiValueProps: ["emojiValueProps"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    container43: makeNodeComponent("container43"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
