// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a87zscS5zAyxUWqfaRXyok
// Component: 5q6vu0sOZbzTG_
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  useTrigger,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: SpLhEqEri3lkmA/component
import Price from "../../Price"; // plasmic-import: pflfYLHUFrOqp9/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: a87zscS5zAyxUWqfaRXyok/projectcss
import * as sty from "./PlasmicProductCard.module.css"; // plasmic-import: 5q6vu0sOZbzTG_/css
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: _JWBIQc0Dw9Hnu/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: -r-fYnkxRYvK-o/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: bYKHgwSwZqdvK2/icon

export const PlasmicProductCard__VariantProps = new Array("small");

export const PlasmicProductCard__ArgProps = new Array(
  "image",
  "slot",
  "children",
  "price",
  "link"
);

function PlasmicProductCard__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__small]: hasVariant(variants, "small", "small")
      })}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <a
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(defaultcss.all, sty.link, {
          [sty.link__small]: hasVariant(variants, "small", "small")
        })}
        href={args.link !== undefined ? args.link : "/item"}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__vW4Px)}
              role={"img"}
              src={
                "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/1070aebbb55841e1aae5ac9f00b39879_9366/adidas_Ultraboost_DNA_x_LEGO(r)_Plates_Shoes_White_FY7690_01_standard.jpg"
              }
            />
          ),

          value: args.image
        })}

        {(
          hasVariant(variants, "small", "small") && triggers.hover_root
            ? true
            : false
        ) ? (
          <div
            className={classNames(defaultcss.all, sty.box__qrbVi, {
              [sty.box__small__qrbViUjRrh]: hasVariant(
                variants,
                "small",
                "small"
              )
            })}
          />
        ) : null}

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box___0HrMg, {
            [sty.box__small___0HrMgUjRrh]: hasVariant(
              variants,
              "small",
              "small"
            )
          })}
        >
          <div className={classNames(defaultcss.all, sty.box__niHYe)}>
            {p.renderPlasmicSlot({
              defaultContents: (
                <Button
                  colors={"lightGray"}
                  icons={"none"}
                  size={"small"}
                  slot={"New"}
                />
              ),

              value: args.slot
            })}

            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              children3={
                <Icon8Icon
                  className={classNames(defaultcss.all, sty.svg___3Juft)}
                  role={"img"}
                />
              }
              children32={
                <Icon8Icon
                  className={classNames(defaultcss.all, sty.svg__a7The)}
                  role={"img"}
                />
              }
              children322={
                <Icon7Icon
                  className={classNames(defaultcss.all, sty.svg__eobmx)}
                  role={"img"}
                />
              }
              children3222={
                <Icon6Icon
                  className={classNames(defaultcss.all, sty.svg__t888S)}
                  role={"img"}
                />
              }
              icons={"five"}
              size={"small"}
              slot={"New"}
            >
              <Icon8Icon
                className={classNames(defaultcss.all, sty.svg__iieur)}
                role={"img"}
              />
            </Button>
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__ebPja)}
          >
            {p.renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__l0Sm
                    )}
                  >
                    {"Product name"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___4XfB
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </React.Fragment>
              ),

              value: args.children
            })}
          </p.Stack>

          <Price
            data-plasmic-name={"price"}
            data-plasmic-override={overrides.price}
            className={classNames("__wab_instance", sty.price)}
            price={p.renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__up3U
                    )}
                  >
                    {"$"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__jcpCq
                    )}
                  >
                    {"88"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ermC3
                    )}
                  >
                    {".99"}
                  </div>
                </React.Fragment>
              ),

              value: args.price
            })}
          />
        </p.Stack>
      </a>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "link", "button", "price"],
  link: ["link", "button", "price"],
  button: ["button"],
  price: ["price"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProductCard__ArgProps,
      internalVariantPropNames: PlasmicProductCard__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicProductCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductCard";
  } else {
    func.displayName = `PlasmicProductCard.${nodeName}`;
  }
  return func;
}

export const PlasmicProductCard = Object.assign(
  // Top-level PlasmicProductCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    button: makeNodeComponent("button"),
    price: makeNodeComponent("price"),
    // Metadata about props expected for PlasmicProductCard
    internalVariantProps: PlasmicProductCard__VariantProps,
    internalArgProps: PlasmicProductCard__ArgProps
  }
);

export default PlasmicProductCard;
/* prettier-ignore-end */
